apiVersion: v1
kind: Service
metadata:
  name: fast-api
spec:
  selector:
    app: fast-api
  type: LoadBalancer  # <- Change from ClusterIP to LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
