apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.0.100-10.0.0.150

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-homelab
  namespace: metallb-system
spec:
  ipAddressPools:
    - metallb-ip-pool
