apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
spec:
  selector:
    app: fast-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80      # Internal service port
      targetPort: 80  # FastAPI container port
      nodePort: 30007 # Exposed NodePort (between 30000-32767)
